Install docs
DyssolTEC/Dyssol-open pull request #121
Opened 2023-04-24 16:43 UTC by LeaRieck

2023-04-24 16:59 UTC, vasylskorych requested changes

2023-04-24 16:59 UTC, vasylskorych commented on DyssolInstallers/Installer_Src_x86_x64/wsl_create_docs.ps1
> +#install dependencies
Remove commented code

2023-04-24 16:59 UTC, vasylskorych commented on DyssolInstallers/Installer_Src_x86_x64/wsl_create_docs.ps1
> +#bash -c "cd $src_path_wsl/$build_path && cmake .. -DCMAKE_INSTALL_PREFIX=../$install_path -DBUILD_BINARIES=NO && make doc && make install"
This also

2023-04-24 19:34 UTC, gladk commented on Utilities/BuildVersion.h
> +#pragma once
Please revert this line ending change.

2023-04-25 15:13 UTC, vasylskorych approved these changes

2023-04-25 17:38 UTC, gladk commented on README.md
> +$ pip install -U sphinx sphinx-rtd-theme breathe
If you use apt installer already, please try to use it also for sphinx theme. 

sudo apt-get install doxygen graphviz python3-breathe python3-sphinx-rtd-theme

2023-04-25 22:09 UTC, vasylskorych commented on README.md
> +$ pip install -U sphinx sphinx-rtd-theme breathe
I would like to, but standard packages are ancient - both Ubuntu 18 and 20 have Sphinx 1.X.X, and ist output is rather ugly.

2023-04-27 14:35 UTC, merged